### ISSUE TITLE
I can connect to the server through browser, but cannot access the content

### ISSUE THREAD

**Issue by ZonicTrout** [Ehren12/C-http-server#2]
When I connect to the http server through firefox, I am unable to load any of the builtin webpages. On the servers cli output, I can see that it connected and it knew that I wanted the index.html page, but it wouldn't send it to me
![$04NotFoundWebpage](https://github.com/Ehren12/C-http-server/assets/117415204/b68b2c05-2e69-49a6-b122-3122ab628941)

**Comment by ZonicTrout** [comment]
also, sorry for not messaging on slack, my school blocks slack and they blocked my vpn too :(

**Comment by Ehren12** [comment]
> When I connect to the http server through firefox, I am unable to load any of the builtin webpages. On the servers cli output, I can see that it connected and it knew that I wanted the index.html page, but it wouldn't send it to me
> 
> ![$04NotFoundWebpage](https://github.com/Ehren12/C-http-server/assets/117415204/b68b2c05-2e69-49a6-b122-3122ab628941)
> 
> 

Most likely you didn't create an index.html file in the view's folder. So it will return a 404 Not Found.
